// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-ext.proto

package com.google.openrtb;

public final class TestExt {
  private TestExt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.openrtb.TestExt.testRequest1);
    registry.add(com.google.openrtb.TestExt.testRequest2);
    registry.add(com.google.openrtb.TestExt.testApp);
    registry.add(com.google.openrtb.TestExt.testContent);
    registry.add(com.google.openrtb.TestExt.testData);
    registry.add(com.google.openrtb.TestExt.testSegment);
    registry.add(com.google.openrtb.TestExt.testDevice);
    registry.add(com.google.openrtb.TestExt.testGeo);
    registry.add(com.google.openrtb.TestExt.testImp);
    registry.add(com.google.openrtb.TestExt.testBanner);
    registry.add(com.google.openrtb.TestExt.testVideo);
    registry.add(com.google.openrtb.TestExt.testNative);
    registry.add(com.google.openrtb.TestExt.testPmp);
    registry.add(com.google.openrtb.TestExt.testDeal);
    registry.add(com.google.openrtb.TestExt.testProducer);
    registry.add(com.google.openrtb.TestExt.testPublisher);
    registry.add(com.google.openrtb.TestExt.testRegs);
    registry.add(com.google.openrtb.TestExt.testSite);
    registry.add(com.google.openrtb.TestExt.testUser);
    registry.add(com.google.openrtb.TestExt.testResponse1);
    registry.add(com.google.openrtb.TestExt.testResponse2);
    registry.add(com.google.openrtb.TestExt.testSeat);
    registry.add(com.google.openrtb.TestExt.testBid);
  }
  public static final int TESTREQUEST1_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest,
      com.google.openrtb.Test.Test1> testRequest1 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTREQUEST2_FIELD_NUMBER = 111;
  /**
   * <code>extend .com.google.openrtb.BidRequest { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest,
      com.google.openrtb.Test.Test2> testRequest2 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test2.class,
        com.google.openrtb.Test.Test2.getDefaultInstance());
  public static final int TESTAPP_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.App { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.App,
      com.google.openrtb.Test.Test1> testApp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTCONTENT_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Content { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Content,
      com.google.openrtb.Test.Test1> testContent = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTDATA_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Data { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Data,
      com.google.openrtb.Test.Test1> testData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTSEGMENT_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Data.Segment { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Data.Segment,
      com.google.openrtb.Test.Test1> testSegment = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTDEVICE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Device { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Device,
      com.google.openrtb.Test.Test1> testDevice = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTGEO_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Geo { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Geo,
      com.google.openrtb.Test.Test1> testGeo = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTIMP_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Impression { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Impression,
      com.google.openrtb.Test.Test1> testImp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTBANNER_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Impression.Banner { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Impression.Banner,
      com.google.openrtb.Test.Test1> testBanner = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTVIDEO_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Impression.Video { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Impression.Video,
      com.google.openrtb.Test.Test1> testVideo = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNATIVE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Impression.Native { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Impression.Native,
      com.google.openrtb.Test.Test1> testNative = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTPMP_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Impression.PMP { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Impression.PMP,
      com.google.openrtb.Test.Test1> testPmp = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTDEAL_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Impression.PMP.Deal { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Impression.PMP.Deal,
      com.google.openrtb.Test.Test1> testDeal = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTPRODUCER_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Producer { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Producer,
      com.google.openrtb.Test.Test1> testProducer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTPUBLISHER_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Publisher { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Publisher,
      com.google.openrtb.Test.Test1> testPublisher = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTREGS_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Regulations { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Regulations,
      com.google.openrtb.Test.Test1> testRegs = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTSITE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.Site { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.Site,
      com.google.openrtb.Test.Test1> testSite = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTUSER_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidRequest.User { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidRequest.User,
      com.google.openrtb.Test.Test1> testUser = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTRESPONSE1_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidResponse { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidResponse,
      com.google.openrtb.Test.Test1> testResponse1 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTRESPONSE2_FIELD_NUMBER = 111;
  /**
   * <code>extend .com.google.openrtb.BidResponse { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidResponse,
      com.google.openrtb.Test.Test2> testResponse2 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test2.class,
        com.google.openrtb.Test.Test2.getDefaultInstance());
  public static final int TESTSEAT_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidResponse.SeatBid { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidResponse.SeatBid,
      com.google.openrtb.Test.Test1> testSeat = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTBID_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.BidResponse.SeatBid.Bid { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtb.BidResponse.SeatBid.Bid,
      com.google.openrtb.Test.Test1> testBid = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016test-ext.proto\022\022com.google.openrtb\032\rop" +
      "enrtb.proto\032\021test-common.proto:O\n\014testRe" +
      "quest1\022\036.com.google.openrtb.BidRequest\030n" +
      " \001(\0132\031.com.google.openrtb.Test1:O\n\014testR" +
      "equest2\022\036.com.google.openrtb.BidRequest\030" +
      "o \001(\0132\031.com.google.openrtb.Test2:N\n\007test" +
      "App\022\".com.google.openrtb.BidRequest.App\030" +
      "n \001(\0132\031.com.google.openrtb.Test1:V\n\013test" +
      "Content\022&.com.google.openrtb.BidRequest." +
      "Content\030n \001(\0132\031.com.google.openrtb.Test1",
      ":P\n\010testData\022#.com.google.openrtb.BidReq" +
      "uest.Data\030n \001(\0132\031.com.google.openrtb.Tes" +
      "t1:[\n\013testSegment\022+.com.google.openrtb.B" +
      "idRequest.Data.Segment\030n \001(\0132\031.com.googl" +
      "e.openrtb.Test1:T\n\ntestDevice\022%.com.goog" +
      "le.openrtb.BidRequest.Device\030n \001(\0132\031.com" +
      ".google.openrtb.Test1:N\n\007testGeo\022\".com.g" +
      "oogle.openrtb.BidRequest.Geo\030n \001(\0132\031.com" +
      ".google.openrtb.Test1:U\n\007testImp\022).com.g" +
      "oogle.openrtb.BidRequest.Impression\030n \001(",
      "\0132\031.com.google.openrtb.Test1:_\n\ntestBann" +
      "er\0220.com.google.openrtb.BidRequest.Impre" +
      "ssion.Banner\030n \001(\0132\031.com.google.openrtb." +
      "Test1:]\n\ttestVideo\022/.com.google.openrtb." +
      "BidRequest.Impression.Video\030n \001(\0132\031.com." +
      "google.openrtb.Test1:_\n\ntestNative\0220.com" +
      ".google.openrtb.BidRequest.Impression.Na" +
      "tive\030n \001(\0132\031.com.google.openrtb.Test1:Y\n" +
      "\007testPmp\022-.com.google.openrtb.BidRequest" +
      ".Impression.PMP\030n \001(\0132\031.com.google.openr",
      "tb.Test1:_\n\010testDeal\0222.com.google.openrt" +
      "b.BidRequest.Impression.PMP.Deal\030n \001(\0132\031" +
      ".com.google.openrtb.Test1:X\n\014testProduce" +
      "r\022\'.com.google.openrtb.BidRequest.Produc" +
      "er\030n \001(\0132\031.com.google.openrtb.Test1:Z\n\rt" +
      "estPublisher\022(.com.google.openrtb.BidReq" +
      "uest.Publisher\030n \001(\0132\031.com.google.openrt" +
      "b.Test1:W\n\010testRegs\022*.com.google.openrtb" +
      ".BidRequest.Regulations\030n \001(\0132\031.com.goog" +
      "le.openrtb.Test1:P\n\010testSite\022#.com.googl",
      "e.openrtb.BidRequest.Site\030n \001(\0132\031.com.go" +
      "ogle.openrtb.Test1:P\n\010testUser\022#.com.goo" +
      "gle.openrtb.BidRequest.User\030n \001(\0132\031.com." +
      "google.openrtb.Test1:Q\n\rtestResponse1\022\037." +
      "com.google.openrtb.BidResponse\030n \001(\0132\031.c" +
      "om.google.openrtb.Test1:Q\n\rtestResponse2" +
      "\022\037.com.google.openrtb.BidResponse\030o \001(\0132" +
      "\031.com.google.openrtb.Test2:T\n\010testSeat\022\'" +
      ".com.google.openrtb.BidResponse.SeatBid\030" +
      "n \001(\0132\031.com.google.openrtb.Test1:W\n\007test",
      "Bid\022+.com.google.openrtb.BidResponse.Sea" +
      "tBid.Bid\030n \001(\0132\031.com.google.openrtb.Test" +
      "1B\tB\007TestExt"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          testRequest1.internalInit(descriptor.getExtensions().get(0));
          testRequest2.internalInit(descriptor.getExtensions().get(1));
          testApp.internalInit(descriptor.getExtensions().get(2));
          testContent.internalInit(descriptor.getExtensions().get(3));
          testData.internalInit(descriptor.getExtensions().get(4));
          testSegment.internalInit(descriptor.getExtensions().get(5));
          testDevice.internalInit(descriptor.getExtensions().get(6));
          testGeo.internalInit(descriptor.getExtensions().get(7));
          testImp.internalInit(descriptor.getExtensions().get(8));
          testBanner.internalInit(descriptor.getExtensions().get(9));
          testVideo.internalInit(descriptor.getExtensions().get(10));
          testNative.internalInit(descriptor.getExtensions().get(11));
          testPmp.internalInit(descriptor.getExtensions().get(12));
          testDeal.internalInit(descriptor.getExtensions().get(13));
          testProducer.internalInit(descriptor.getExtensions().get(14));
          testPublisher.internalInit(descriptor.getExtensions().get(15));
          testRegs.internalInit(descriptor.getExtensions().get(16));
          testSite.internalInit(descriptor.getExtensions().get(17));
          testUser.internalInit(descriptor.getExtensions().get(18));
          testResponse1.internalInit(descriptor.getExtensions().get(19));
          testResponse2.internalInit(descriptor.getExtensions().get(20));
          testSeat.internalInit(descriptor.getExtensions().get(21));
          testBid.internalInit(descriptor.getExtensions().get(22));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.openrtb.OpenRtb.getDescriptor(),
          com.google.openrtb.Test.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
