// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-common.proto

package com.google.openrtb;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Test1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string test1 = 1;
    /**
     * <code>required string test1 = 1;</code>
     */
    boolean hasTest1();
    /**
     * <code>required string test1 = 1;</code>
     */
    java.lang.String getTest1();
    /**
     * <code>required string test1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getTest1Bytes();
  }
  /**
   * Protobuf type {@code com.google.openrtb.Test1}
   */
  public static final class Test1 extends
      com.google.protobuf.GeneratedMessage
      implements Test1OrBuilder {
    // Use Test1.newBuilder() to construct.
    private Test1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test1 defaultInstance;
    public static Test1 getDefaultInstance() {
      return defaultInstance;
    }

    public Test1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              test1_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.openrtb.Test.internal_static_com_google_openrtb_Test1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.openrtb.Test.internal_static_com_google_openrtb_Test1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.openrtb.Test.Test1.class, com.google.openrtb.Test.Test1.Builder.class);
    }

    public static com.google.protobuf.Parser<Test1> PARSER =
        new com.google.protobuf.AbstractParser<Test1>() {
      public Test1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string test1 = 1;
    public static final int TEST1_FIELD_NUMBER = 1;
    private java.lang.Object test1_;
    /**
     * <code>required string test1 = 1;</code>
     */
    public boolean hasTest1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string test1 = 1;</code>
     */
    public java.lang.String getTest1() {
      java.lang.Object ref = test1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          test1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string test1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTest1Bytes() {
      java.lang.Object ref = test1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      test1_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTest1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTest1Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTest1Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.openrtb.Test.Test1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.openrtb.Test.Test1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.openrtb.Test.Test1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.openrtb.Test.Test1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.openrtb.Test1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.openrtb.Test.Test1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.openrtb.Test.internal_static_com_google_openrtb_Test1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.openrtb.Test.internal_static_com_google_openrtb_Test1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.openrtb.Test.Test1.class, com.google.openrtb.Test.Test1.Builder.class);
      }

      // Construct using com.google.openrtb.Test.Test1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        test1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.openrtb.Test.internal_static_com_google_openrtb_Test1_descriptor;
      }

      public com.google.openrtb.Test.Test1 getDefaultInstanceForType() {
        return com.google.openrtb.Test.Test1.getDefaultInstance();
      }

      public com.google.openrtb.Test.Test1 build() {
        com.google.openrtb.Test.Test1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.openrtb.Test.Test1 buildPartial() {
        com.google.openrtb.Test.Test1 result = new com.google.openrtb.Test.Test1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.test1_ = test1_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.openrtb.Test.Test1) {
          return mergeFrom((com.google.openrtb.Test.Test1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.openrtb.Test.Test1 other) {
        if (other == com.google.openrtb.Test.Test1.getDefaultInstance()) return this;
        if (other.hasTest1()) {
          bitField0_ |= 0x00000001;
          test1_ = other.test1_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTest1()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.openrtb.Test.Test1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.openrtb.Test.Test1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string test1 = 1;
      private java.lang.Object test1_ = "";
      /**
       * <code>required string test1 = 1;</code>
       */
      public boolean hasTest1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string test1 = 1;</code>
       */
      public java.lang.String getTest1() {
        java.lang.Object ref = test1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          test1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string test1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTest1Bytes() {
        java.lang.Object ref = test1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string test1 = 1;</code>
       */
      public Builder setTest1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        test1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string test1 = 1;</code>
       */
      public Builder clearTest1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        test1_ = getDefaultInstance().getTest1();
        onChanged();
        return this;
      }
      /**
       * <code>required string test1 = 1;</code>
       */
      public Builder setTest1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        test1_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.openrtb.Test1)
    }

    static {
      defaultInstance = new Test1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.openrtb.Test1)
  }

  public interface Test2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string test2 = 1;
    /**
     * <code>required string test2 = 1;</code>
     */
    boolean hasTest2();
    /**
     * <code>required string test2 = 1;</code>
     */
    java.lang.String getTest2();
    /**
     * <code>required string test2 = 1;</code>
     */
    com.google.protobuf.ByteString
        getTest2Bytes();
  }
  /**
   * Protobuf type {@code com.google.openrtb.Test2}
   */
  public static final class Test2 extends
      com.google.protobuf.GeneratedMessage
      implements Test2OrBuilder {
    // Use Test2.newBuilder() to construct.
    private Test2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Test2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Test2 defaultInstance;
    public static Test2 getDefaultInstance() {
      return defaultInstance;
    }

    public Test2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Test2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              test2_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.openrtb.Test.internal_static_com_google_openrtb_Test2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.openrtb.Test.internal_static_com_google_openrtb_Test2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.openrtb.Test.Test2.class, com.google.openrtb.Test.Test2.Builder.class);
    }

    public static com.google.protobuf.Parser<Test2> PARSER =
        new com.google.protobuf.AbstractParser<Test2>() {
      public Test2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Test2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Test2> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string test2 = 1;
    public static final int TEST2_FIELD_NUMBER = 1;
    private java.lang.Object test2_;
    /**
     * <code>required string test2 = 1;</code>
     */
    public boolean hasTest2() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string test2 = 1;</code>
     */
    public java.lang.String getTest2() {
      java.lang.Object ref = test2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          test2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string test2 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTest2Bytes() {
      java.lang.Object ref = test2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      test2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTest2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTest2Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTest2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.openrtb.Test.Test2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.openrtb.Test.Test2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.openrtb.Test.Test2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.openrtb.Test.Test2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.openrtb.Test2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.openrtb.Test.Test2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.openrtb.Test.internal_static_com_google_openrtb_Test2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.openrtb.Test.internal_static_com_google_openrtb_Test2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.openrtb.Test.Test2.class, com.google.openrtb.Test.Test2.Builder.class);
      }

      // Construct using com.google.openrtb.Test.Test2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        test2_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.openrtb.Test.internal_static_com_google_openrtb_Test2_descriptor;
      }

      public com.google.openrtb.Test.Test2 getDefaultInstanceForType() {
        return com.google.openrtb.Test.Test2.getDefaultInstance();
      }

      public com.google.openrtb.Test.Test2 build() {
        com.google.openrtb.Test.Test2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.openrtb.Test.Test2 buildPartial() {
        com.google.openrtb.Test.Test2 result = new com.google.openrtb.Test.Test2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.test2_ = test2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.openrtb.Test.Test2) {
          return mergeFrom((com.google.openrtb.Test.Test2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.openrtb.Test.Test2 other) {
        if (other == com.google.openrtb.Test.Test2.getDefaultInstance()) return this;
        if (other.hasTest2()) {
          bitField0_ |= 0x00000001;
          test2_ = other.test2_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTest2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.openrtb.Test.Test2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.openrtb.Test.Test2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string test2 = 1;
      private java.lang.Object test2_ = "";
      /**
       * <code>required string test2 = 1;</code>
       */
      public boolean hasTest2() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string test2 = 1;</code>
       */
      public java.lang.String getTest2() {
        java.lang.Object ref = test2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          test2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string test2 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTest2Bytes() {
        java.lang.Object ref = test2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string test2 = 1;</code>
       */
      public Builder setTest2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        test2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string test2 = 1;</code>
       */
      public Builder clearTest2() {
        bitField0_ = (bitField0_ & ~0x00000001);
        test2_ = getDefaultInstance().getTest2();
        onChanged();
        return this;
      }
      /**
       * <code>required string test2 = 1;</code>
       */
      public Builder setTest2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        test2_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.openrtb.Test2)
    }

    static {
      defaultInstance = new Test2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.openrtb.Test2)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_openrtb_Test1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_openrtb_Test1_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_openrtb_Test2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_openrtb_Test2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021test-common.proto\022\022com.google.openrtb\"" +
      "\026\n\005Test1\022\r\n\005test1\030\001 \002(\t\"\026\n\005Test2\022\r\n\005test" +
      "2\030\001 \002(\tB\006B\004Test"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_google_openrtb_Test1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_google_openrtb_Test1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_openrtb_Test1_descriptor,
              new java.lang.String[] { "Test1", });
          internal_static_com_google_openrtb_Test2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_google_openrtb_Test2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_google_openrtb_Test2_descriptor,
              new java.lang.String[] { "Test2", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
