// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test-native-ext.proto

package com.google.openrtb;

public final class TestNExt {
  private TestNExt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.google.openrtb.TestNExt.testNRequest1);
    registry.add(com.google.openrtb.TestNExt.testNRequest2);
    registry.add(com.google.openrtb.TestNExt.testNReqAsset);
    registry.add(com.google.openrtb.TestNExt.testNReqTitle);
    registry.add(com.google.openrtb.TestNExt.testNReqImage);
    registry.add(com.google.openrtb.TestNExt.testNReqVideo);
    registry.add(com.google.openrtb.TestNExt.testNReqData);
    registry.add(com.google.openrtb.TestNExt.testNResponse1);
    registry.add(com.google.openrtb.TestNExt.testNResponse2);
    registry.add(com.google.openrtb.TestNExt.testNRespAsset);
    registry.add(com.google.openrtb.TestNExt.testNRespTitle);
    registry.add(com.google.openrtb.TestNExt.testNRespImage);
    registry.add(com.google.openrtb.TestNExt.testNRespVideo);
    registry.add(com.google.openrtb.TestNExt.testNRespData);
    registry.add(com.google.openrtb.TestNExt.testNRespLink);
  }
  public static final int TESTNREQUEST1_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeRequest { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest,
      com.google.openrtb.Test.Test1> testNRequest1 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNREQUEST2_FIELD_NUMBER = 111;
  /**
   * <code>extend .com.google.openrtb.NativeRequest { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest,
      com.google.openrtb.Test.Test2> testNRequest2 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test2.class,
        com.google.openrtb.Test.Test2.getDefaultInstance());
  public static final int TESTNREQASSET_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest.Asset,
      com.google.openrtb.Test.Test1> testNReqAsset = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNREQTITLE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset.Title { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest.Asset.Title,
      com.google.openrtb.Test.Test1> testNReqTitle = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNREQIMAGE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset.Image { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest.Asset.Image,
      com.google.openrtb.Test.Test1> testNReqImage = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNREQVIDEO_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset.Video { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest.Asset.Video,
      com.google.openrtb.Test.Test1> testNReqVideo = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNREQDATA_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeRequest.Asset.Data { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeRequest.Asset.Data,
      com.google.openrtb.Test.Test1> testNReqData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPONSE1_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse,
      com.google.openrtb.Test.Test1> testNResponse1 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPONSE2_FIELD_NUMBER = 111;
  /**
   * <code>extend .com.google.openrtb.NativeResponse { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse,
      com.google.openrtb.Test.Test2> testNResponse2 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test2.class,
        com.google.openrtb.Test.Test2.getDefaultInstance());
  public static final int TESTNRESPASSET_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse.Asset { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse.Asset,
      com.google.openrtb.Test.Test1> testNRespAsset = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPTITLE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse.Asset.Title { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse.Asset.Title,
      com.google.openrtb.Test.Test1> testNRespTitle = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPIMAGE_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse.Asset.Image { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse.Asset.Image,
      com.google.openrtb.Test.Test1> testNRespImage = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPVIDEO_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse.Asset.Video { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse.Asset.Video,
      com.google.openrtb.Test.Test1> testNRespVideo = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPDATA_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse.Asset.Data { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse.Asset.Data,
      com.google.openrtb.Test.Test1> testNRespData = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());
  public static final int TESTNRESPLINK_FIELD_NUMBER = 110;
  /**
   * <code>extend .com.google.openrtb.NativeResponse.Link { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.openrtb.OpenRtbNative.NativeResponse.Link,
      com.google.openrtb.Test.Test1> testNRespLink = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.openrtb.Test.Test1.class,
        com.google.openrtb.Test.Test1.getDefaultInstance());

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025test-native-ext.proto\022\022com.google.open" +
      "rtb\032\024openrtb-native.proto\032\021test-common.p" +
      "roto:S\n\rtestNRequest1\022!.com.google.openr" +
      "tb.NativeRequest\030n \001(\0132\031.com.google.open" +
      "rtb.Test1:S\n\rtestNRequest2\022!.com.google." +
      "openrtb.NativeRequest\030o \001(\0132\031.com.google" +
      ".openrtb.Test2:Y\n\rtestNReqAsset\022\'.com.go" +
      "ogle.openrtb.NativeRequest.Asset\030n \001(\0132\031" +
      ".com.google.openrtb.Test1:_\n\rtestNReqTit" +
      "le\022-.com.google.openrtb.NativeRequest.As",
      "set.Title\030n \001(\0132\031.com.google.openrtb.Tes" +
      "t1:_\n\rtestNReqImage\022-.com.google.openrtb" +
      ".NativeRequest.Asset.Image\030n \001(\0132\031.com.g" +
      "oogle.openrtb.Test1:_\n\rtestNReqVideo\022-.c" +
      "om.google.openrtb.NativeRequest.Asset.Vi" +
      "deo\030n \001(\0132\031.com.google.openrtb.Test1:]\n\014" +
      "testNReqData\022,.com.google.openrtb.Native" +
      "Request.Asset.Data\030n \001(\0132\031.com.google.op" +
      "enrtb.Test1:U\n\016testNResponse1\022\".com.goog" +
      "le.openrtb.NativeResponse\030n \001(\0132\031.com.go",
      "ogle.openrtb.Test1:U\n\016testNResponse2\022\".c" +
      "om.google.openrtb.NativeResponse\030o \001(\0132\031" +
      ".com.google.openrtb.Test2:[\n\016testNRespAs" +
      "set\022(.com.google.openrtb.NativeResponse." +
      "Asset\030n \001(\0132\031.com.google.openrtb.Test1:a" +
      "\n\016testNRespTitle\022..com.google.openrtb.Na" +
      "tiveResponse.Asset.Title\030n \001(\0132\031.com.goo" +
      "gle.openrtb.Test1:a\n\016testNRespImage\022..co" +
      "m.google.openrtb.NativeResponse.Asset.Im" +
      "age\030n \001(\0132\031.com.google.openrtb.Test1:a\n\016",
      "testNRespVideo\022..com.google.openrtb.Nati" +
      "veResponse.Asset.Video\030n \001(\0132\031.com.googl" +
      "e.openrtb.Test1:_\n\rtestNRespData\022-.com.g" +
      "oogle.openrtb.NativeResponse.Asset.Data\030" +
      "n \001(\0132\031.com.google.openrtb.Test1:Y\n\rtest" +
      "NRespLink\022\'.com.google.openrtb.NativeRes" +
      "ponse.Link\030n \001(\0132\031.com.google.openrtb.Te" +
      "st1B\nB\010TestNExt"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          testNRequest1.internalInit(descriptor.getExtensions().get(0));
          testNRequest2.internalInit(descriptor.getExtensions().get(1));
          testNReqAsset.internalInit(descriptor.getExtensions().get(2));
          testNReqTitle.internalInit(descriptor.getExtensions().get(3));
          testNReqImage.internalInit(descriptor.getExtensions().get(4));
          testNReqVideo.internalInit(descriptor.getExtensions().get(5));
          testNReqData.internalInit(descriptor.getExtensions().get(6));
          testNResponse1.internalInit(descriptor.getExtensions().get(7));
          testNResponse2.internalInit(descriptor.getExtensions().get(8));
          testNRespAsset.internalInit(descriptor.getExtensions().get(9));
          testNRespTitle.internalInit(descriptor.getExtensions().get(10));
          testNRespImage.internalInit(descriptor.getExtensions().get(11));
          testNRespVideo.internalInit(descriptor.getExtensions().get(12));
          testNRespData.internalInit(descriptor.getExtensions().get(13));
          testNRespLink.internalInit(descriptor.getExtensions().get(14));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.openrtb.OpenRtbNative.getDescriptor(),
          com.google.openrtb.Test.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
